### ISSUE TITLE
queries with UUIDs don't pass spec

### ISSUE THREAD

**Issue by arohner** [walkable-server/walkable#103]
Same setup as #102 ,

Using the query `(q db [{[:foo.bar/by-id "30c00191-3d33-4aa7-b9ac-1662f61466f8"] [:foo.bar/id :foo.bar/bbq]}])`, sends the uuid as a string, which will be rejected by postgres as comparing "character varying vs. uuid". If instead, you add a `#uuid`, walkable throws a spec validation error:

```clojure
(q db [{[:foo.bar/by-id #uuid "30c00191-3d33-4aa7-b9ac-1662f61466f8"] [:foo.bar/id :foo.bar/bbq]}])
AssertionError Assert failed: Invalid expression: [:= :foo.bar/id #uuid "30c00191-3d33-4aa7-b9ac-1662f61466f8"]
(not= :clojure.spec.alpha/invalid form)  walkable.sql-query-builder.expressions/parameterize (expressions.cljc:475)
```

**Comment by rboyd** [comment]
blocked on this. any workaround?

**Comment by myguidingstar** [comment]
I'm working on it now

**Comment by myguidingstar** [comment]
You can use things like `#uuid "30c00191-3d33-4aa7-b9ac-1662f61466f8"` anywhere as walkable s-expressions now

**Comment by rboyd** [comment]
@myguidingstar thanks so much. It may just be me, I'm pretty new to walkable, but now I get this exception using bits from master.

```
AssertionError Assert failed: Invalid expression: 759c94e5-5ac7-44aa-b737-541d812141f8
(not= :clojure.spec.alpha/invalid form)  walkable.sql-query-builder.expressions/compile-to-string (expressions.cljc:515)
```
my setup:

```clojure
(def compiled-floor-plan
  (floor-plan/compile-floor-plan
   {:emitter emitter/postgres-emitter
    :cardinality {:users/by-user-id :one}
    :idents {:users/all "users"
             :users/by-user-id :users/user-id}}))

(let [user-id #uuid "759c94e5-5ac7-44aa-b737-541d812141f8"
      db {:spec {:connection-uri "jdbc:postgresql://etcetc"}}
      my-run-query jdbc/query
      my-db (:spec db)
      my-query `[{[:users/by-user-id ~user-id] [:users/email]}]
              results (sync-parser {::sqb/sql-db my-db
                              ::sqb/run-query  my-run-query
                              ::sqb/floor-plan compiled-floor-plan}
                                   my-query)]
  results)
```

```sql
CREATE TABLE users
(
user_id UUID DEFAULT uuid_generate_v4(),
email VARCHAR UNIQUE ,
password_digest VARCHAR,
first_name VARCHAR NOT NULL,
last_name VARCHAR NOT NULL,
CONSTRAINT users_pkey PRIMARY KEY (user_id)
);
```

**Comment by myguidingstar** [comment]
I've just tested, your code works on my machine. (you need `{:true-columns [:users/user-id :users/email ...]}` in your floor-plan)
This #uuid feature is specific to postgres, did you have this `(require 'walkable.sql-query-builder.impl.postgres)`?

Also, I've already pushed latest snapshot (`[walkable "1.2.0-SNAPSHOT"]
`) from master to clojars, so no need to dig into `master`.

**Comment by myguidingstar** [comment]
@rboyd btw, I think using singular nouns for table names will result in better api. There are lots of discussions about that on the web, eg:
https://www.teamten.com/lawrence/programming/use-singular-nouns-for-database-table-names.html
