### ISSUE TITLE
Quoting and Oracle

### ISSUE THREAD

**Issue by RokLenarcic** [walkable-server/walkable#109]
Oracle identifiers default to upper case when creating DB objects. This means that people working with existing oracle databases will almost always be working with objects(tables, columns) with uppercase names. 

Generally Oracle will convert to upper case any unquoted identifiers, in that if you write `select id from person`, it will select column `ID` from table `PERSON`. Same goes for DDL statements (which is why oracle databases are mostly in upper case). Walkable emits quoted table/column identitiers however, which are lower cased, so oracle will loudly complain about tables not existing. 

Even if one can force all DDLs, that is identifiers, to lower case when creating the table, then any tool or app selecting from it MUST quote identifiers, otherwise you also get an error. `select id from person` will say that table doesn't exist, if your table is named `person`.

I am not sure what the solution is, but it makes using walkable with oracle kind of a non-starter.

**Comment by myguidingstar** [comment]
Thanks for reporting this.
I don't have on Oracle db at hand. Long story short, how do you translate this mysql query to an Oracle one?
```sql
SELECT 2 AS `person/two`, `person`.`number` AS `person/number` FROM `person` WHERE `person`.`number` = 1 AND `person/two` = 2
```

**Comment by RokLenarcic** [comment]
It depends on what case your actual tables names are:

If UPPER case or not specified, you can use unquoted table/column names in either lower or uppercase:

```SELECT 2 AS "person/two", person.number AS "person/number" FROM person```
or 

```SELECT 2 AS "person/two", PERSON.NUMBER AS "person/number" FROM PERSON```

If you use quoting you must match the case when table was created (and 90%+ of oracle databases have uppercased names as that is the default). Case of aliases - `AS` isn't a problem.

```SELECT 2 AS "person/two", "PERSON"."NUMBER" AS "person/number" FROM "PERSON"```

Obviously if someone created the database with explicitly lower case names then your initial code works (with different quotes).

```SELECT 2 AS "person/two", "person"."number" AS "person/number" FROM "person"```

What I suggest is that you add an option that will make all table column names in upper case. This will cover most standard Oracle databases as they exist in the wild.

**Comment by myguidingstar** [comment]
I see. So this can be considered an use case of #17.
In the meantime, if your table and column names are safe to use without quotes, then you can specify walkable to use a pair of empty string (`["", ""]`) as quote marks.

**Comment by RokLenarcic** [comment]
Empty quote marks don't solve this, sadly, since aliases like `person/number` need to be quoted.
