### ISSUE TITLE
add :grouping

### ISSUE THREAD

**Issue by myguidingstar** [walkable-server/walkable#124]
```clj
;; floor-plan
{:idents {[:people/all :people/by-country] "person"}
 :pseudo-columns {:person/person-count [:count :person/id]}
 :grouping {:people/by-country 
           {:group-by [:person/country]
            :having [:< 0 [:count-* ]]}}}
;; query
`[{:people/by-country [:person/person-count :person/country]}]
```
output
```sql
select count(person.id) as "person/person-count",
 person.country as "person/country"
from person
group by person.country
having 0 < count(*)
```

**Comment by efraimmgon** [comment]
Why does `group by` require a floor-plan description for it to work?

**Comment by myguidingstar** [comment]
actually I was considering whether to support 'group by' at all or not.
Floor-plan is meant to be private while query is made public so you have to be very careful with what is allowed in query. (Of course you can make queries internally right from server app, but as a library Walkable has to cover the "worst" case: untrusted clients)
Group-by and other aggregating operations are expensive and requires knowledge of the database schema, which you can't expect from untrusted clients.
Via floor-plan, you dictate specifically which group-by operations are allowed (and create index for the column(s) in use!)

Regarding the workaround, you can write a Pathom plugin to make arbitrary sql queries like this one. I guess it's straightforward enough
https://github.com/walkable-server/realworld-fulcro/blob/master/src/conduit/handler/walkable.clj#L201

**Comment by myguidingstar** [comment]
Okay, I'll implement this thing soon. Thanks for your input.

Here's the workaround for the above example:
```clj
(def people-by-country-query
"select person.name AS \"person/name\", person.country AS \"person/country\"
from person
group by person.country
having 0 < count(*)")
;; your plugin:

(def people-by-country-resolver
  {:people/by-country 
   (fn [{::sqb/keys [run-query sql-db]}]
     (into [] (run-query sql-db [people-by-country-query])))})

(def pathom-parser
  (p/parser
    {::p/plugins
     [(p/env-plugin
        {::p/reader
         [sqb/pull-entities
          p/map-reader
          p/env-placeholder-reader
          ;; add your new plugin here:
          people-by-country-resolver]})]}))
```
