### ISSUE TITLE
release a non-snapshot version to clojars?

### ISSUE THREAD

**Issue by peter-wilkins-mayden** [walkable-server/walkable#127]
Hi
Thanks for the good work with walkable.
Would like to use it at work but the snapshot release won't pass code review.
Would you consider releasing a non-snapshot version to clojars?

**Comment by myguidingstar** [comment]
hey Peter,
thanks for your interest in using walkable at work. I think walkable is quite stable now, given lots of integration tests added recently. I myself was thinking about a release, too. It's just my mind occupied with the pull request that I can't make a proper announcement :)
I'm going to make 1.1.0-rc1 later today.
Btw, when you have time, please drop a line in #walkable clojurian slack channel to tell about how you're using walkable at work. I would love to hear more about people's use cases.

**Comment by myguidingstar** [comment]
deployed

**Comment by green-coder** [comment]
@myguidingstar When you release a version, please don't leave "snapshot" in the version.
Historically, snapshots are not a "specific version" and refer to the latest commit on a branch.
