### ISSUE TITLE
floor-plan/compile-floor-plan always gives NullPointerException

### ISSUE THREAD

**Issue by zilti** [walkable-server/walkable#162]
walkable `1.2.0-SNAPSHOT` always gives an NPE when calling `floor-plan/compile-floor-plan`.

I tried to compile the `{:idents {:people/all "person"}}` floor plan from the docs, it fails.

**Comment by myguidingstar** [comment]
Walkable is not producing helpful error messages right now. I'm sorry about that.
There's a note in the floor plan doc: `For clarity, only relevant parts of the floor-plan are included`
But the doc doesn't say which keys are required in a floor plan `map`.

I guess you miss `emitter`. Please see its doc and add it to your floor plan.
