### ISSUE TITLE
Add support for Pathom Connect?

### ISSUE THREAD

**Issue by adamfeldman** [walkable-server/walkable#163]
If I understand the history correctly, Walkable was initially implemented before Pathom's [`Connect`](https://wilkerlucio.github.io/pathom/#Connect) abstraction existed. 

Has there been any past exploration or discussion of how/if Walkable could be modified/extended to support Pathom Connect? Who else out there is interested in using or working on this?

I believe there would be a good amount of interest in a SQL backend for [Fulcro RAD](https://github.com/fulcrologic/fulcro-rad) -- currently Fulcro RAD is experimental, and has only Datomic support. 

My understanding is that Pathom Connect support is necessary for a Fulcro RAD backend to provide the full potential of its enhanced developer ergonomics. It is expected that Fulcro RAD will be a major factor in driving future Fulcro adoption, and by extension related projects such as Walkable.

Pathom Connect has [various benefits](https://wilkerlucio.github.io/pathom/#Connect):

> 1. Auto-complete of graph queries in [tools for data exploration](https://github.com/wilkerlucio/pathom-viz).
> 2. Graph edge generation from the index’s connection information.
> 3. [Multiple ways to reach a given attribute, automatically resolved via known reachable edges and transitive relations.](https://www.youtube.com/watch?v=IS3i3DTUnAI)

**Comment by adamfeldman** [comment]
Please note I am not yet familiar with Fulcro RAD's implementation, or whether it would benefit from work done in Walkable (and vice-versa).

I just found the partial implementation of a SQL backend for Fulcro RAD: https://github.com/fulcrologic/fulcro-rad/blob/master/src/main/com/fulcrologic/rad/database_adapters/postgresql.clj

**Comment by myguidingstar** [comment]
New public api has just been merged to master. Pathom Connect support is part of it. Docs coming soon
