### ISSUE TITLE
First documentation result incorrect?

### ISSUE THREAD

**Issue by teodorlu** [walkable-server/walkable#164]
Hello!

This is the first documented result:

```clojure
{[:person/by-id 1]
 {:person/id   1
  :person/name "Mary"
  :person/age  20
  {:person/pet {:pet/name              "Tom"
                :pet/favorite-location "garden"}}}}
```

As far as I can see, that contains a map with an odd number of elements in it. An error, perhaps?

Have an otherwise nice day,
Teodor

**Comment by myguidingstar** [comment]
Nice catch! The documentation source is here, contribution is highly welcome
https://github.com/walkable-server/docs

**Comment by teodorlu** [comment]
Cool!

I'd love to contribute, but frankly, not having used walkable, I don't know what it should be.

Is this right?

```clojure
{[:person/by-id 1]
 {:person/id   1
  :person/name "Mary"
  :person/age  20
  :person/pet  {:pet/name              "Tom"
                :pet/favorite-location "garden"}}}
```

**Comment by myguidingstar** [comment]
Yup, that's correct

**Comment by teodorlu** [comment]
I'll send a PR :)

**Comment by teodorlu** [comment]
PR: https://github.com/walkable-server/docs/pull/1

Closing this!
