### ISSUE TITLE
allow custom keyword to table/column function

### ISSUE THREAD

**Issue by myguidingstar** [walkable-server/walkable#17]

**Comment by myguidingstar** [comment]
in place of `sqb/split-keyword`

**Comment by skrat** [comment]
This would be hugely beneficial to walkable adoption. IMO it would be for the best if table / column could be specified in schema for each particular table and column, or, using a function. But IMO, the former is more important if you want walkable to be adopted for existing projects.

**Comment by myguidingstar** [comment]
Hi @skrat, please update to `[walkable "1.1.0-SNAPSHOT"]`.
Walkable "schema" has been renamed to `floor-plan`.
The thing discussed here is covered in:
https://walkable.gitbook.io/walkable/doc/emitter
