### ISSUE TITLE
Serialize query result to valid json

### ISSUE THREAD

**Issue by eko234** [walkable-server/walkable#179]
Hi, I'm trying to use walkable to build a rest json api, so far the concept seems great, the thing is I'm kinda noob to clojure but I do get the philosophy of simplicity and I'm ok with it, I know I can write some data manipulation function to turn walkable query results into valid maps or arrays to be serialized by ring middleware, (I'm using ring as my http server), but I wanted to know if there is an easier or built-in way to go about it.

**Comment by myguidingstar** [comment]
hi,
imo the "built-in" way for such things should live in ring side, not walkable. Maybe `ring-middleware-format` is what you're looking for?

**Comment by eko234** [comment]
> hi,
> imo the "built-in" way for such things should live in ring side, not walkable. Maybe `ring-middleware-format` is what you're looking for?

Thanks.
