### ISSUE TITLE
Other database supports

### ISSUE THREAD

**Issue by jichon** [walkable-server/walkable#37]
I'm trying to test `walkable` on a `fulcro` setup with `postgres` database and it's generating a query syntax that is not supported by postgres. I dig thru the code and it looks likethe generation select queries with back tick. Or possible that I'm missing something here. Can you help? Thanks

**Comment by myguidingstar** [comment]
Thanks for reporting. There should be an option for which quote string to use. I'm working on it today. In the mean time can you give me an example of what that SELECT should look like for postgres to work in contrast to currently generated by walkable?

**Comment by myguidingstar** [comment]
For instance how would you do this in postgres?
```sql
SELECT 2 AS `a/two`, `person`.`number` AS `person/number` FROM `person` WHERE `person`.`number` = 1 AND `a/two` = 2
```

**Comment by myguidingstar** [comment]
Postgres doesn't allow using pseudo columns `person/two` in WHERE statements

**Comment by myguidingstar** [comment]
Both SQLite and Postgres work with `"` quotes. We can switch to that by default

**Comment by myguidingstar** [comment]
for UNION queries, SQLite requires `SELECT * FROM (query-1) UNION SELECT * FROM (query-2) ` while postgres only works with `query-1 UNION query-2`

**Comment by myguidingstar** [comment]
@jichon please check out latest master. I've tested with both mysql and postgresql

**Comment by myguidingstar** [comment]
for sqlite, UNION needs some more work

**Comment by jichon** [comment]
@myguidingstar thank you for the update. i'll give that a shot

**Comment by myguidingstar** [comment]
all done :)

**Comment by jichon** [comment]
@myguidingstar nice it's working after adding `:quote-marks sqb/quotation-marks`

**Comment by myguidingstar** [comment]
you're welcome. I've created a new channel #walkable on clojurians slack. I'd love to hear more from people's use cases
