### ISSUE TITLE
Pre-Condtion in `sqb/compile-schema` suggests only `columns` and `idents` is needed, but fails later for several other keys

### ISSUE THREAD

**Issue by christoph-frick** [walkable-server/walkable#54]
See https://github.com/walkable-server/walkable/blob/9621f1ca5fba0dbed06872c80ede5a7b646af3c7/src/walkable/sql_query_builder.cljc#L422

Due to the use of `flatten-multi-keys` later, also the following keys are basically mandatory for a schema:

- `joins`
- `cardinality`
- `extra-conditions`

While the first two most likely always exist anyways in any non-trivial example, `extra-conditions` might actually not be needed and the assert thrown later in `flatten-multi-keys` is way more confusing than just making them `req-un` for now?

**Comment by myguidingstar** [comment]
Great discovery! I think the above three should not be mandatory.
flatten-multi-keys should only be applied after checking for non nil. Eg:
```clj
(flatten-multi-keys extra-conditions)
```
should become
```clj
(when extra-conditions
  (flatten-multi-keys extra-conditions))
```
are you willing to make another pr? :)

**Comment by christoph-frick** [comment]
What about putting them in the `:or` as empty maps?

https://github.com/walkable-server/walkable/blob/9621f1ca5fba0dbed06872c80ede5a7b646af3c7/src/walkable/sql_query_builder.cljc#L419

**Comment by myguidingstar** [comment]
that should work, too. Maybe that would save us from some null point exception headaches that I can't contemplate atm
